export const DEFAULT_REMINDERS = [
  "A transição para a vida adulta não é uma corrida. Respire.",
  "Cada pequena vitória merece ser celebrada hoje.",
  "Você está fazendo o melhor que pode com o que tem.",
  "O presente é o único lugar onde você realmente pode viver.",
  "Não se compare com o palco dos outros. Sua jornada tem o seu próprio ritmo.",
  "Confie no processo. Suas buscas estão te levando exatamente onde você precisa estar.",
  "Está tudo bem não saber tudo ainda. Você ainda está aprendendo.",
  "A pessoa que você está se tornando importa mais do que a que você era.",
  "Você merece dedicar tanta atenção a si mesmo quanto aos outros.",
  "Crescer dói, mas estagnar dói muito mais. Orgulhe-se do seu progresso.",
  "Seja gentil consigo hoje. Amanhã é mais um passo.",
  "O amadurecimento é lento. Seja gentil com o seu tempo.",
  "Respire. O futuro não chegou e você não precisa resolver tudo hoje.",
  "Sua ansiedade mostra que você se importa, mas não é uma previsão do futuro.",
  "Você tem permissão para mudar de ideia, de sonho, de direção.",
  "Pequenas ações alinhadas com seus valores valem mais do que grandes metas vazias.",
  "Você está mais perto do que imagina.",
  "Cada desafio superado é um degrau na construção da sua melhor versão.",
  "A vida não precisa fazer sentido para ninguém, apenas para você.",
  "Você já sobreviveu a tudo que achava que não conseguiria. Isso importa.",
  "Não existe momento perfeito. Existe agora.",
  "Seu valor não depende de quanto você produz.",
  "Você merece estar ao redor de pessoas que te escolhem de verdade.",
  "Às vezes, o maior avanço é apenas continuar.",
  "Você não precisa provar nada a ninguém hoje.",
  "A paciência com você mesmo é uma forma de amor.",
  "Cada dia é uma nova chance de ser quem você quer ser.",
  "O silêncio também é resposta. Às vezes, a mais honesta.",
  "Você é suficiente do jeito que você é.",
  "Uma coisa de cada vez. Só uma.",
  "Você não precisa ter tudo resolvido para ser feliz agora.",
  "Descansar não é desistir. É reconhecer seus limites com sabedoria.",
  "O que você está sentindo hoje é válido, mesmo sem explicação.",
  "Nenhum capítulo difícil define o livro inteiro.",
  "Você merece o mesmo cuidado que oferece às pessoas que ama.",
  "Errar é parte do aprendizado, não evidência de fracasso.",
  "Hoje, basta dar um passo. Só um.",
  "Você não precisa ser produtivo para ter valor.",
  "A gentileza começa por dentro. Seja gentil com você.",
  "Sua história não terminou. O melhor pode estar à frente.",
  "Nem todo silêncio precisa ser preenchido.",
  "Você é capaz de mais do que acredita nos dias difíceis.",
  "Suas emoções são mensageiras, não inimigas.",
  "Está tudo bem pedir ajuda. Isso é coragem, não fraqueza.",
  "Cada amanhecer é uma página em branco. O que você quer escrever?",
  "O cansaço que você sente é real. Honre-o.",
  "Você não precisa ser a versão mais feliz de si mesmo o tempo todo.",
  "Confiar no tempo é também uma forma de agir.",
  "Você está se tornando quem você foi feito para ser.",
  "Pequenos passos ainda são progresso.",
  "Nem todo dia precisa ser épico para ser bom.",
  "Sua presença importa, mesmo quando não percebe.",
  "O que você mais precisar ouvir hoje: você está fazendo um bom trabalho.",
  "Soltar o que não está em suas mãos também é força.",
  "Você não deve nada a ninguém além de ser honesto consigo mesmo.",
  "Há dignidade em continuar tentando, mesmo devagar.",
  "Seu corpo carrega muito. Trate-o com gratidão.",
  "Você é mais do que seus erros passados.",
  "Uma pausa não é um retrocesso.",
  "Hoje pode ser difícil. Amanhã é um novo começo.",
  "Você tem o direito de mudar de ideia sem se justificar.",
  "Estar presente em um momento simples é um presente para si.",
  "Às vezes, não ter resposta é a resposta mais honesta.",
  "O seu ritmo não precisa acompanhar o de ninguém.",
  "Você já atravessou coisas que achava que não conseguiria. Lembre disso.",
  "Cuidar de si não é egoísmo, é sobrevivência.",
  "Hoje, que tal fazer algo só porque você gosta?",
  "Você não precisa justificar seu cansaço.",
  "A vulnerabilidade é o caminho para conexões reais.",
  "Você merece tempo para pensar, sentir e ser.",
  "Cada escolha que te alinha com seus valores é uma vitória.",
  "Há algo de corajoso em continuar mesmo sem certeza.",
  "Você não precisa de aprovação para existir do seu jeito.",
  "O amanhã tem seus próprios recursos. Não tente carregá-lo hoje.",
  "Seja curioso sobre quem você está se tornando.",
  "Você já plantou sementes que ainda não viu brotar.",
  "Às vezes, a coisa mais produtiva é descansar.",
  "Você merece paz, não apenas pausas.",
  "Suas lutas não te definem, mas sua resposta a elas sim.",
  "Não existe forma errada de ser você.",
  "Mesmo nos dias cinzas, você ainda importa.",
  "O que é urgente nem sempre é importante. Priorize o que importa.",
  "Você não é seus pensamentos. Você é quem os observa.",
  "Hoje é um bom dia para ser gentil com alguém, incluindo você.",
  "Cada conversa honesta é uma forma de cuidado.",
  "A vida é mais do que o que aparece nas telas.",
  "Você é digno de afeto sem precisar ganhar.",
  "Um passo atrás às vezes abre espaço para dois à frente.",
  "O que você sente hoje é temporário. Você não é.",
  "Você tem uma história única que ninguém mais pode contar.",
  "Fazer menos com mais presença vale mais do que fazer muito no automático.",
  "Você não precisa consertar tudo hoje.",
  "A vida é feita de momentos simples que mais tarde viram memórias.",
  "Você não é menos por ter dias difíceis.",
  "O que você cuida, cresce. Cuide de você.",
  "Cada vez que você foi honesto consigo foi um ato de coragem.",
  "Você tem permissão para existir no seu próprio espaço.",
  "Hoje, o suficiente é suficiente.",
  "Há algo de lindo em começar de novo, mesmo pela centésima vez.",
  "Você merece sonhos que assustam um pouco.",
  "O presente não precisa ser perfeito para ser precioso.",
  "Você está mais conectado ao seu caminho do que parece.",
  "Às vezes, o que parece atraso é na verdade preparação.",
  "Você tem o direito de sentir o que sente sem explicar.",
  "Cada dia que você cuida de si é um dia bem vivido.",
  "Não compare seu começo com o meio de alguém.",
  "Você é capaz de criar algo significativo com o que tem.",
  "O amor próprio é uma prática diária, não um destino.",
  "Hoje, escolha uma coisa que te faça bem. Só uma.",
  "Você não precisa carregar o peso de todos os outros.",
  "Sua história ainda está sendo escrita.",
  "Acredite que pequenas mudanças criam grandes transformações.",
  "Você tem o direito de ocupar espaço no mundo.",
  "Não existe linha de chegada para o autoconhecimento.",
  "Você está exatamente onde precisa estar agora.",
  "O que você aprende nas fases difíceis fica para sempre.",
  "Hoje, escolha a versão de você que você quer ser.",
  "Você é válido mesmo nos dias em que não acredita nisso.",
  "Sentir demais não é fraqueza. É sensibilidade.",
  "Sua voz importa. Use-a.",
  "Você não precisa de motivo para se cuidar.",
  "Às vezes, o maior presente é um momento de silêncio.",
  "Você tem dignidade em cada fase da vida.",
  "O medo que você sente hoje pode ser o motor de amanhã.",
  "Você merece relacionamentos que te deixam ser você mesmo.",
  "Nada do que você viveu foi desperdiçado.",
  "Você tem mais força do que imagina nos dias bons.",
  "Hoje pode ser simples. Simples é suficiente.",
  "Você não precisa se apressar para crescer.",
  "Confiar em si mesmo é a fundação de tudo.",
  "Você tem muito a oferecer, mesmo quando não vê.",
  "A cura não é linear. Ela vai e volta, e tudo bem.",
  "Você merece uma vida que faz sentido para você.",
  "Às vezes, não fazer nada é exatamente o que precisa ser feito.",
  "Você é a única pessoa que pode viver a sua vida.",
  "Cada experiência difícil expandiu sua capacidade de entender o mundo.",
  "Você tem o poder de reescrever a narrativa que tem sobre si.",
  "Hoje, reconheça pelo menos uma coisa boa em você.",
  "Você não precisa de validação para saber seu valor.",
  "A vida adulta é difícil. Você não está falhando, está aprendendo.",
  "Você merece paz interior, não apenas realizações externas.",
  "Às vezes, cuidar do básico já é um grande ato de amor próprio.",
  "Você tem o direito de descansar sem culpa.",
  "O que você planta hoje, você colhe em outro momento.",
  "Você não é obrigado a estar bem o tempo todo.",
  "Cada dia que você tenta é um dia que importa.",
  "Sua sensibilidade é um dom, não um defeito.",
  "Você está fazendo o melhor que pode com o que sabe hoje.",
  "Amanhã é outro capítulo. Hoje, cuide deste.",
  "Você não precisa ser perfeito para ser amado.",
  "A inconsistência faz parte do processo humano.",
  "Você tem permissão para sentir raiva, tristeza, confusão.",
  "Hoje, seja seu próprio aliado.",
  "Você é mais resiliente do que seus medos sugerem.",
  "Há beleza no processo, não só no resultado.",
  "Você não é suas redes sociais. Você é muito mais.",
  "Às vezes, a melhor decisão é esperar um pouco mais.",
  "Você tem o direito de estabelecer limites sem culpa.",
  "Cada momento de honestidade consigo mesmo é crescimento.",
  "Você é suficiente agora, não quando atingir a próxima meta.",
  "Não existe jornada errada. Existe a sua.",
  "Você merece ter pessoas que te apoiam de verdade.",
  "O que você não sabe ainda não é razão para se diminuir.",
  "Cada vez que você se escolheu, você cresceu.",
  "Você não precisa entender tudo para seguir em frente.",
  "Hoje, permita-se sentir gratidão por algo pequeno.",
  "Você já é suficiente para começar.",
  "A jornada de dentro para fora é a mais importante.",
  "Você não precisa ganhar o direito de existir.",
  "Às vezes, o silêncio entre duas pessoas é conforto.",
  "Você tem mais clareza do que imagina quando para de correr.",
  "Cada escolha de amor próprio muda o trajeto.",
  "Você é digno de ser feliz, não apenas de sobreviver.",
  "Hoje, permita que alguém cuide de você também.",
  "Você não deve ao mundo uma versão polida de si mesmo.",
  "O desconforto que sente pode ser crescimento em andamento.",
  "Você tem o direito de recomeçar quantas vezes precisar.",
  "Às vezes, o avanço mais bonito não aparece nas fotos.",
  "Você carrega uma história que tem valor.",
  "A honestidade consigo mesmo abre o caminho para tudo.",
  "Você merece manhãs com calma.",
  "Nem todo plano precisa estar pronto para começar.",
  "Você não é menos por precisar de apoio.",
  "Cada dia que você não desistiu foi uma vitória.",
  "Suas imperfeições são parte do que te faz único.",
  "Você tem o direito de não saber o que quer ainda.",
  "Às vezes, o melhor cuidado é dormir cedo.",
  "Você está construindo algo, mesmo quando não vê.",
  "O amor que você dá a outros merece voltar para você também.",
  "Você não precisa ser forte o tempo todo.",
  "Hoje, celebre o simples fato de estar aqui.",
  "Você tem o poder de escolher onde coloca sua atenção.",
  "Às vezes, dizer não é o maior ato de respeito próprio.",
  "Você merece clareza, não apenas movimento.",
  "Cada pessoa que cruzou seu caminho te ensinou algo.",
  "Você não está atrasado. Está no seu tempo.",
  "O que você sente hoje tem nome. Você não está sozinho nisso.",
  "Você tem valor fora do que produz ou realiza.",
  "Às vezes, a resposta chega quando você para de forçar.",
  "Você é mais do que seus momentos de insegurança.",
  "Hoje, seja curioso ao invés de julgador consigo mesmo.",
  "Você tem o direito de ocupar espaço sem pedir desculpa.",
  "A vida que você quer começa com escolhas de hoje.",
  "Você não precisa esperar para começar a se tratar bem.",
  "Às vezes, o que parece regressão é reorganização.",
  "Você merece momentos de leveza no meio do esforço.",
  "Cada pensamento gentil sobre si mesmo importa.",
  "Você tem muito mais a descobrir sobre quem é.",
  "O presente sempre carrega sementes do futuro.",
  "Você não é suas preocupações.",
  "Hoje, faça uma coisa que você adiou por medo.",
  "Você tem permissão para não estar disponível para tudo.",
  "Às vezes, o maior presente é se ver com olhos de compaixão.",
  "Você está mais inteiro do que os pedaços quebrados sugerem.",
  "Cada conversa que você tem consigo mesmo molda quem você é.",
  "Você não precisa de permissão para ser feliz agora.",
  "O ritmo de cada um é diferente. O seu é legítimo.",
  "Você merece cuidar do seu corpo com gentileza.",
  "Às vezes, a coragem é só aparecer para o dia.",
  "Você tem mais recursos internos do que imagina.",
  "Hoje, escolha uma pessoa para agradecer, inclusive você.",
  "Você não é responsável por consertar o que não quebrou.",
  "As fases de dúvida também ensinam.",
  "Você merece amizades que te fazem ser mais você mesmo.",
  "Não existe idade certa para descobrir quem você é.",
  "Você tem o direito de sentir saudade, raiva e esperança ao mesmo tempo.",
  "Hoje, permita-se existir sem performance.",
  "Você já ajudou alguém sem perceber. Isso importa.",
  "Às vezes, o mais honesto que você pode fazer é descansar.",
  "Você merece relacionamentos com espaço para crescer.",
  "Cada escolha que te respeita é uma escolha certa.",
  "Você não precisa ter tudo ao mesmo tempo.",
  "O que você está passando hoje vai te ensinar algo amanhã.",
  "Você tem o direito de ser imperfeito e ainda assim inteiro.",
  "Às vezes, a pausa é o que permite o avanço.",
  "Você carrega mais luz do que percebe nos dias escuros.",
  "Hoje, escolha um pensamento gentil sobre si.",
  "Você não é o pior cenário que imaginou.",
  "Há coragem em continuar sem certeza.",
  "Você merece sonhar em voz alta.",
  "Às vezes, a maior transformação começa em silêncio.",
  "Você não precisa de uma razão para se tratar bem.",
  "O cuidado com você é também cuidado com os outros.",
  "Você tem uma perspectiva única que o mundo precisa.",
  "Hoje, permita que o momento seja apenas o que é.",
  "Você não é obrigado a carregar o passado para sempre.",
  "Cada respiração consciente é um retorno a você.",
  "Você merece celebrar o que conseguiu sem diminuir.",
  "Às vezes, o próximo passo é simplesmente parar de correr.",
  "Você tem o poder de ressignificar o que viveu.",
  "Hoje, trate-se como trataria alguém que você ama.",
  "Você não é menos porque está crescendo devagar.",
  "O que você planta em silêncio muitas vezes floresce em público.",
  "Você merece ocupar espaço no mundo sem desculpas.",
  "Às vezes, a maior bravura é admitir que precisa de ajuda.",
  "Você tem o direito de ser feliz sem culpa.",
  "Hoje, reconheça o quanto você evoluiu nos últimos meses.",
  "Você não precisa de aprovação para seguir seu caminho.",
  "Cada passo dado com intenção tem peso e valor.",
  "Você é capaz de criar conexões profundas.",
  "Às vezes, o silêncio dentro de você precisa ser ouvido.",
  "Você merece uma vida com espaço para o que importa.",
  "O caminho não é reto. E tudo bem.",
  "Você tem permissão para ser exatamente onde está hoje.",
  "Hoje, respire fundo e reconheça que você ainda está aqui.",
  "Você não é apenas o que os outros enxergam.",
  "Às vezes, demorar é sinal de que você está levando a sério.",
  "Você merece rir sem motivo grande.",
  "O que você cuida hoje é o que te sustenta amanhã.",
  "Você tem o direito de não seguir o roteiro que traçaram para você.",
  "Hoje, permita-se ser movido por algo além da obrigação.",
  "Você não precisa conquistar nada hoje para ter valor.",
  "Às vezes, o ato mais revolucionário é simplesmente se aceitar.",
  "Você merece paz que não depende de nada externo.",
  "Cada pequena mudança interna cria uma nova realidade.",
  "Você é parte de algo maior do que consegue enxergar agora.",
  "Hoje, permita que a leveza entre onde costuma entrar o peso.",
  "Você não precisa entender o passado para construir o futuro.",
  "Às vezes, a vitória mais bonita é a que só você viu.",
  "Você merece tempo para não fazer nada importante.",
  "Cada vez que você se perdoou, você cresceu.",
  "Você tem o direito de existir fora dos papéis que os outros criaram para você.",
  "Hoje, escolha pelo menos uma coisa que te traga alegria real.",
  "O seu esforço importa, mesmo quando os resultados demoram.",
  "Você não é definido pelos seus dias mais difíceis.",
  "Às vezes, o maior presente é uma conversa honesta consigo mesmo.",
  "Você merece acordar com paz, não com ansiedade.",
  "Cada limitação que você aceita com honestidade vira sabedoria.",
  "Você tem permissão para ser humano, com todas as contradições que isso implica.",
  "Hoje, um pequeno ato de cuidado próprio já é suficiente.",
  "Você não precisa correr atrás de uma versão ideal de si.",
  "Às vezes, parar é a única forma de encontrar o caminho.",
  "Você merece relacionamentos onde pode ser exatamente quem é.",
  "O que você aprende em silêncio muitas vezes vale mais do que o que aprende em correria.",
  "Você não está sozinho no que está sentindo. Milhares sentem o mesmo.",
  "Hoje, celebre o fato de que você ainda está tentando.",
  "Você tem o direito de ocupar espaço sem se desculpar por existir.",
  "Às vezes, a melhor versão de si mesmo é a que simplesmente aparece.",
  "Você já foi mais corajoso do que imagina. Vai ser de novo.",
  "Hoje e sempre: você importa.",
];

export const THEMED_REMINDERS: Record<string, string[]> = {
  ansiedade: [
    "Respire. O futuro ainda não chegou e você não precisa resolver tudo hoje.",
    "Sua ansiedade é um sinal de que você se importa, mas ela não é uma previsão do futuro.",
    "Está tudo bem não estar bem o tempo todo. Acolha seu sentir."
  ],
  identidade: [
    "Você é muito mais do que suas conquistas ou o seu cargo. Sua essência é única.",
    "Não se compare com o palco dos outros. Sua jornada tem o seu próprio ritmo.",
    "A pessoa que você está se tornando é mais importante do que a que você costumava ser."
  ],
  solidão: [
    "A solitude é o encontro consigo mesmo. Aproveite esse espaço para se ouvir.",
    "Estar sozinho não significa estar desamparado. É um momento de recarregar.",
    "Sua própria companhia é preciosa. Cultive o amor por quem você é no silêncio."
  ],
  propósito: [
    "O propósito não é um destino, é a forma como você caminha todos os dias.",
    "Pequenas ações alinhadas com seus valores valem mais do que grandes metas vazias.",
    "Confie no processo. Suas buscas estão te levando exatamente onde você precisa estar."
  ],
  crescimento: [
    "Crescer dói, mas estagnar dói muito mais. Orgulhe-se de quão longe você chegou.",
    "Cada desafio superado é um degrau na construção da sua melhor versão.",
    "O amadurecimento é um processo lento. Seja gentil com o seu tempo."
  ]
};
